// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvEe__OfOFrTyZ5WfTYorvhGnT8taqGM4',
    appId: '1:962119603372:web:ed5c3e749f068e8cf5bb09',
    messagingSenderId: '962119603372',
    projectId: 'mymeteo-147a3',
    authDomain: 'mymeteo-147a3.firebaseapp.com',
    storageBucket: 'mymeteo-147a3.appspot.com',
    measurementId: 'G-5CFN42KSDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN2o9nSkp9gkd-zdD5cu07riJMQbWg__4',
    appId: '1:962119603372:android:66ecfbe095c17a47f5bb09',
    messagingSenderId: '962119603372',
    projectId: 'mymeteo-147a3',
    storageBucket: 'mymeteo-147a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8t1KPj0JQdCvwl6v2oUqlvjVdjNZUX8E',
    appId: '1:962119603372:ios:241e26f2e90f2665f5bb09',
    messagingSenderId: '962119603372',
    projectId: 'mymeteo-147a3',
    storageBucket: 'mymeteo-147a3.appspot.com',
    iosClientId: '962119603372-gqq15v64r7urpsnvjrh6n98vb6n5evcq.apps.googleusercontent.com',
    iosBundleId: 'com.example.myMeteo',
  );
}
